my_string = input('введите строку: ')
print('длинна строки ',len(my_string),' символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])